name: "build"
on:
  pull_request:
    branches: master
  push:
    branches: master
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        # Nix Flakes doesn't work on shallow clones
        fetch-depth: 0
    - uses: cachix/install-nix-action@v11
      with:
        install_url: https://github.com/numtide/nix-flakes-installer/releases/download/nix-2.4pre20201221_9fab14a/install
        # Configure Nix to enable flakes
        extra_nix_config: |
          experimental-features = nix-command flakes
    # Run the general flake checks
    #- run: nix flake check
    - run: nix build -L
    # Verify that the main program builds
    - run: nix shell -c echo OK
    # Verify nixpkgs version number
    - run: nix-instantiate --eval -E '(import <nixpkgs> {}).lib.version'
